<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-JamillyHamid/blob/main/Atividade_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

rng = np.random.default_rng(42)

# 1.
z = np.zeros(10)
print("1)", z, z.dtype, z.shape)

# 2.
u = np.ones(10, dtype=np.float64)
print("\n2)", u, u.dtype)

# 3.
seq = np.arange(10)
print("\n3)", seq)

# 4.
m_3 = np.arange(9).reshape(3, 3)
print("\n4)\n", m_3)

# 5.
v = np.array([1, 2, 0, 0, 4, 0])
idx_nz = np.nonzero(v)[0]
print("\n5)", idx_nz)

# 6.
lin = np.linspace(0, 1, 12)
print("\n6)", lin)

# 7.
I5 = np.eye(5)
print("7)\n", I5)

# 8.
r3 = rng.random((3, 3, 3))
print("\n8) shape", r3.shape)

# 9.
M = rng.random((10, 10))
print("\n9) min/max:", M.min(), M.max())

# 10.
x = np.array([1, 2, 3, 4, 5], dtype=float)
x_std = (x - x.mean()) / x.std(ddof=0)
print("\n10)", x_std, "mean=", x_std.mean(), "std=", x_std.std())

# 11.
arr = np.array([1, 2, 3], dtype=np.int32).astype(np.float32).astype(np.int64)
print("\n11)", arr, arr.dtype)

# 12.
a = np.array([2, 5, 7, 1, 9])
cl = np.clip(a, 0, 5)
print("\n12)", cl)

# 13.
rev = np.flip(np.arange(10))
print("\n13)", rev)

# 14.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h = np.hstack([a, b])
vstack = np.vstack([a, b])
print("\n14) h=", h, "\n   v=\n", vstack)

# 15.
D4 = np.diag(np.full(4, 5.0))
print("\n15)\n", D4)

# 16.
A = np.arange(12).reshape(3, 4)
print("\n16) sum_rows=", A.sum(axis=1), "sum_cols=", A.sum(axis=0))

# 17.
integers = rng.integers(0, 10, size=100)
freq = np.bincount(integers, minlength=10)
print("\n17)", freq)

# 18.
v = np.arange(20)
sel = v[1::3]
print("\n18)", sel)

# 19.
vals = np.arange(20)
mask = (vals % 2 == 0)
print("\n19)", vals[mask])

# 20.
ll = np.array([[1, 2, 3], [4, 5, 6]])
print("\n20)", ll.shape, ll.dtype)

# 21.
dates = np.arange(np.datetime64('2025-01-01'), np.datetime64('2025-01-08'))
print("\n21)", dates)

# 22.
A = np.array([[1., 2., 3.], [4., 5., 6.]])
A_centered = A - A.mean(axis=0)
print("\n22)\n", A_centered)

# 23.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
elem = a * b
dotp = a @ b
print("\n23) elem=", elem, "dot=", dotp)

# 24.
A = np.arange(12).reshape(3, 4)
A[:, [0, 2]] = A[:, [2, 0]]
print("\n24)\n", A)

1) [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64 (10,)

2) [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64

3) [0 1 2 3 4 5 6 7 8 9]

4)
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

5) [0 1 4]

6) [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
7)
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

8) shape (3, 3, 3)

9) min/max: 0.007362269751005512 0.9691763773477239

10) [-1.41421356 -0.70710678  0.          0.70710678  1.41421356] mean= 0.0 std= 0.9999999999999999

11) [1 2 3] int64

12) [2 5 5 1 5]

13) [9 8 7 6 5 4 3 2 1 0]

14) h= [1 2 3 4 5 6] 
   v=
 [[1 2 3]
 [4 5 6]]

15)
 [[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]

16) sum_rows= [ 6 22 38] sum_cols= [12 15 18 21]

17) [ 7 13 13  9 11 13 10  5  6 13]

18) [ 1  4  7 10 13 16 19]

19) [ 0  2  4  6  8 10 12 14 16 18]

20) (2, 3) int64

21) ['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-0

In [10]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

rng = np.random.default_rng(42)

# 25.
B = np.arange(6).reshape(2, 3)
r = B.ravel()
f = B.flatten()
r[0] = 99
print("25) B mod ravel:\n", B, "\nflatten é cópia? f[0]=", f[0])

# 26.
i, j = np.indices((8, 8))
board = (i + j) % 2
print("\n26)\n", board)

# 27.
x = np.arange(-5, 6)
y = np.where(x < 0, 0, x)
print("\n27)", y)

# 28.
big = rng.random(1_000_000)
mean_big = big.mean()
err = abs(mean_big - 0.5)
print("\n28) mean=", mean_big, "abs error=", err)

# 29.
a = np.array([1, 2, 3])[:, None]
b = np.array([10, 20, 30, 40])[None, :]
somas = a + b
print("\n29)\n", somas)

# 30.
def conv1d_valid(s, k):
    kf = np.flip(k)
    windows = sliding_window_view(s, k.size)
    return (windows * kf).sum(axis=1)

s = np.array([1, 2, 3, 4, 5])
k = np.array([1, 0, -1])
print("\n30)", conv1d_valid(s, k))

# 31.
A = rng.normal(size=(5, 4))
A_min = A.min(axis=0)
A_max = A.max(axis=0)
den = np.where(A_max > A_min, A_max - A_min, 1.0)
A01 = (A - A_min) / den
print("\n31)\n", A01)

# 32.
A = np.array([[3, 9], [1, 4], [2, 5]])
order = np.argsort(A[:, 1])
A_sorted = A[order]
print("\n32)\n", A_sorted)

# 33.
x = np.array([3, 1, 2, 3, 2, 3, 1])
vals, first_idx = np.unique(x, return_index=True)
counts = np.bincount(x, minlength=vals.max()+1)[vals]
print("\n33) uniques=", vals, "counts=", counts, "first_idx=", first_idx)

# 34.
P = rng.normal(size=(6, 2))
G = P @ P.T
sq = np.sum(P**2, axis=1, keepdims=True)
D2 = sq + sq.T - 2*G
D = np.sqrt(np.maximum(D2, 0.0))
print("\n34) dist shape:", D.shape)

# 35.
X = rng.standard_normal((1000, 3))
cov = np.cov(X, rowvar=False)
corr = np.corrcoef(X, rowvar=False)
print("\n35) cov shape", cov.shape, "corr shape", corr.shape)

# 36.
y = np.array([2, 0, 1, 2])
onehot = np.eye(y.max()+1)[y]
print("\n36)\n", onehot.astype(int))

25) B mod ravel:
 [[99  1  2]
 [ 3  4  5]] 
flatten é cópia? f[0]= 0

26)
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

27) [0 0 0 0 0 0 1 2 3 4 5]

28) mean= 0.5000264761740889 abs error= 2.6476174088907456e-05

29)
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]

30) [2 2 2]

31)
 [[0.75760422 0.41161893 1.         0.17020407]
 [0.         0.         0.81108456 0.49829758]
 [0.67735438 0.83422344 0.95007083 1.        ]
 [1.         0.7634631  0.         0.        ]
 [0.21777619 1.         0.31801306 0.37424146]]

32)
 [[1 4]
 [2 5]
 [3 9]]

33) uniques= [1 2 3] counts= [2 2 3] first_idx= [1 2 0]

34) dist shape: (6, 6)

35) cov shape (3, 3) corr shape (3, 3)

36)
 [[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
